[package]
name = "npuzzle"
version = "0.1.0"
authors = ["vcombey <vcombey@student.42.fr>"]

[dependencies]
lazy_static = "1.1.0"
num-traits = "0.2.5"
derive-new = "0.5.5"
rand = "0.5.5"
serde = "1.0.77"
getopts = "0.2"
bincode = "1.0.1"
serde_derive = "1.0.77"
sdl2 = "0.31.0"